### ISSUE TITLE
[Header][front-page] Logo sizes

### ISSUE THREAD

**Issue by mariovillagra** [CELTAB/site-fpti#1]
El tamanho del logo no es el correcto.
El logo no es igual al del layOut

**Comment by cristhian-urunaga** [comment]
Modificación de posición, tamaño: 826afb1dd52fe92607194a0831e7551f0596701f

**Comment by cristhian-urunaga** [comment]
Modificación de posición, tamaño: 826afb1dd52fe92607194a0831e7551f0596701f (cerrado)
