### ISSUE TITLE
[front-page][banner] "Search" Block - style

### ISSUE THREAD

**Issue by mariovillagra** [CELTAB/site-fpti#11]
El block de búsqueda no esta acorde al layout.
*Icono
*Color
*Posición
*Tamaño

**Comment by mariovillagra** [comment]
Modificación de posición, tamaño: adb8da61249da778bb560b54e67bc5314922ee87

**Comment by gvuyk** [comment]
cerrado con d731a4ae7e5fb09dc88f7e6b2c7b76cce1fc7ef7

**Comment by gvuyk** [comment]
falta traduccion

**Comment by mariovillagra** [comment]
4fb32ef999cfd1bff180905b20ee62502ff8a7cc cerrado
