### ISSUE TITLE
Move the custom module to the folder "custom"

### ISSUE THREAD

**Issue by mariovillagra** [CELTAB/site-fpti#21]
**Es necesario declara cuales fueron los módulos modificados y moverlos a la carpeta:**
~/site/all/modules/custom
Para evitar errores al actualizar el CORE DRUPAL.

**To Do**
* Crear la carpeta [custom]
* Crear el archivo README.txt en la carpeta [custom] y declar los modulos modicados
* Mover los modulos a la nueva carpeta 

:cow2: :shit:

**Comment by gvuyk** [comment]
Modulos modificados:
* tb_megamenu
* nice_menus

**Comment by mariovillagra** [comment]
old_fpti

**Comment by cristhian-urunaga** [comment]
* lang_dropdown
* views_fluid_grid

**Comment by mariovillagra** [comment]
Cerrado con a9a0167297cf0f10703b9b8c96bfa2fd1129a7da
