### ISSUE TITLE
[menu-institucional] New regions 

### ISSUE THREAD

**Issue by mariovillagra** [CELTAB/site-fpti#30]
**To Do**

- Banner en negativo
- Eslogan en Positivo
- Menu Institucional en Positivo
- Menu Institucional style

**Comment by mariovillagra** [comment]
Nueva región con 305ccfe8f8576e1792f920ad166d17a4eb7f9d6f

**Comment by cristhian-urunaga** [comment]
Banner negativo: ok 71ebe18f1ee4e2c95ee138802b60d8b4ee849842

**Comment by mariovillagra** [comment]
cerrado con ce8a9f5218a763950197b89c0eb3cff1be8ad283
