### ISSUE TITLE
[block-news] modify existing regions

### ISSUE THREAD

**Issue by mariovillagra** [CELTAB/site-fpti#31]
Son necesarios dos regiones

**to Do**

* 2 nuevas view para las noticias
* link para ver mas noticias 
* mini banner

**Comment by mariovillagra** [comment]
Regiones creadas con 305ccfe8f8576e1792f920ad166d17a4eb7f9d6f

**Comment by cristhian-urunaga** [comment]
Cerrado con el commit: dfee57ab5e3f1e549c1b1e352fd41f4e2b0ad8af
