### ISSUE TITLE
[front-page][banner] Styles

### ISSUE THREAD

**Issue by mariovillagra** [CELTAB/site-fpti#9]
El banner no esta acorde al layout

**Comment by cristhian-urunaga** [comment]
Cerrado con 32fde2056b8ca81a104f84088a8692d71d934b41

**Comment by gvuyk** [comment]
posicionamieto  y color de fondo, de acuerdo al layout

**Comment by gvuyk** [comment]
Cerrado con 5b60602843aa29fae35ebbe498bbb2d6782be9ae
